package scholar

import (
	"strings"
	"time"
)

// PDFBehavior describes how the fake serves a paper's PDF.
type PDFBehavior string

const (
	PDFOK          PDFBehavior = "ok"          // serve the fixture bytes
	PDFUnavailable PDFBehavior = "unavailable" // 503 forever ("publisher is down")
	PDFNotPDF      PDFBehavior = "html"        // 200 with an HTML body ("bot wall")
)

// Paper is one arXiv record the fake knows about.
type Paper struct {
	ID        string // canonical arXiv id, no version suffix
	Title     string
	Abstract  string
	Authors   []string
	Published time.Time
	Updated   time.Time
	PDF       string // fixture file name under fixtures/pdf
	Behavior  PDFBehavior
	// EPrint, when set, is served as the TeX source (tar.gz); otherwise 404
	// so the worker falls back to the PDF parser.
	EPrint []byte
}

var day = 24 * time.Hour

// Catalog is the deterministic arXiv the test stand sees. IDs starting with
// 2399 are "broken" papers for failure scenarios; 2301.* are healthy.
var Catalog = []Paper{
	{
		ID:        "2301.00001",
		Title:     "Test Paper One: Deterministic Fixtures for Integration Tests",
		Abstract:  "We describe a five page fixture whose third page carries a hypothesis marker.",
		Authors:   []string{"Alice Example", "Bob Sample"},
		Published: time.Date(2023, 1, 1, 10, 0, 0, 0, time.UTC),
		Updated:   time.Date(2023, 1, 1, 10, 0, 0, 0, time.UTC),
		PDF:       "paper-5p.pdf",
		Behavior:  PDFOK,
	},
	{
		ID:        "2301.00002",
		Title:     "Test Paper Two: A Single Page Is Enough",
		Abstract:  "A one page fixture for upload and deduplication scenarios.",
		Authors:   []string{"Carol Fixture"},
		Published: time.Date(2023, 1, 2, 10, 0, 0, 0, time.UTC),
		Updated:   time.Date(2023, 1, 2, 10, 0, 0, 0, time.UTC),
		PDF:       "paper-1p.pdf",
		Behavior:  PDFOK,
	},
	{
		ID:        "2301.00003",
		Title:     "Test Paper Three: Trending Feed Filler A",
		Abstract:  "Third fixture paper, present so the trending feed has several entries.",
		Authors:   []string{"Dan Feed", "Eve Feed"},
		Published: time.Date(2023, 1, 3, 10, 0, 0, 0, time.UTC),
		Updated:   time.Date(2023, 1, 5, 10, 0, 0, 0, time.UTC),
		PDF:       "paper-5p.pdf",
		Behavior:  PDFOK,
	},
	{
		ID:        "2301.00004",
		Title:     "Test Paper Four: Trending Feed Filler B",
		Abstract:  "Fourth fixture paper.",
		Authors:   []string{"Frank Feed"},
		Published: time.Date(2023, 1, 4, 10, 0, 0, 0, time.UTC),
		Updated:   time.Date(2023, 1, 4, 10, 0, 0, 0, time.UTC),
		PDF:       "paper-5p.pdf",
		Behavior:  PDFOK,
	},
	{
		ID:        "2301.00005",
		Title:     "Test Paper Five: Trending Feed Filler C",
		Abstract:  "Fifth fixture paper.",
		Authors:   []string{"Grace Feed"},
		Published: time.Date(2023, 1, 5, 10, 0, 0, 0, time.UTC),
		Updated:   time.Date(2023, 1, 5, 10, 0, 0, 0, time.UTC),
		PDF:       "paper-5p.pdf",
		Behavior:  PDFOK,
	},
	{
		ID:        "2399.99901",
		Title:     "Broken Paper: Publisher Refuses the PDF",
		Abstract:  "Metadata resolves, but every PDF download answers 503.",
		Authors:   []string{"Hank Failure"},
		Published: time.Date(2023, 9, 9, 10, 0, 0, 0, time.UTC),
		Updated:   time.Date(2023, 9, 9, 10, 0, 0, 0, time.UTC),
		PDF:       "paper-1p.pdf",
		Behavior:  PDFUnavailable,
	},
	{
		ID:        "2399.99902",
		Title:     "Broken Paper: Bot Wall Instead of a PDF",
		Abstract:  "Metadata resolves, but the PDF link returns an HTML page.",
		Authors:   []string{"Ivy Failure"},
		Published: time.Date(2023, 9, 9, 11, 0, 0, 0, time.UTC),
		Updated:   time.Date(2023, 9, 9, 11, 0, 0, 0, time.UTC),
		PDF:       "not-a-pdf.pdf",
		Behavior:  PDFNotPDF,
	},
}

// Synthetic ids let a scenario mint a fresh paper per run on a stand that
// keeps its database: 2350.NNNNN is healthy, 2351.NNNNN refuses the PDF
// (503), 2352.NNNNN answers HTML instead of a PDF. Anything else outside the
// catalog is unknown, as on the real arXiv.
const (
	SyntheticOK          = "2350."
	SyntheticUnavailable = "2351."
	SyntheticNotPDF      = "2352."
)

func synthetic(id string) (Paper, bool) {
	var behavior PDFBehavior
	switch {
	case strings.HasPrefix(id, SyntheticOK):
		behavior = PDFOK
	case strings.HasPrefix(id, SyntheticUnavailable):
		behavior = PDFUnavailable
	case strings.HasPrefix(id, SyntheticNotPDF):
		behavior = PDFNotPDF
	default:
		return Paper{}, false
	}
	if len(id) != len("2350.00000") {
		return Paper{}, false
	}
	pdf := "paper-5p.pdf"
	if behavior == PDFNotPDF {
		pdf = "not-a-pdf.pdf"
	}
	when := time.Date(2023, 5, 1, 10, 0, 0, 0, time.UTC)
	return Paper{
		ID:        id,
		Title:     "Synthetic Fixture Paper " + id + ": Minted For One Test Run",
		Abstract:  "A synthetic arXiv record generated by fake-scholar for id " + id + ".",
		Authors:   []string{"Syn Thetic"},
		Published: when,
		Updated:   when,
		PDF:       pdf,
		Behavior:  behavior,
	}, true
}

// Find returns the catalog entry for an id with or without a version suffix.
func Find(id string) (Paper, bool) {
	id = canonical(id)
	if p, ok := synthetic(id); ok {
		return p, true
	}
	for _, p := range Catalog {
		if p.ID == id {
			return p, true
		}
	}
	return Paper{}, false
}

// Healthy lists papers whose PDF is served normally (what the feed shows).
func Healthy() []Paper {
	out := make([]Paper, 0, len(Catalog))
	for _, p := range Catalog {
		if p.Behavior == PDFOK {
			out = append(out, p)
		}
	}
	return out
}

// DOIRecord is one DOI the fake Crossref (and optionally OpenAlex) knows.
// Crossref answers /works/{doi} with the record; OpenAlex answers
// /works/https://doi.org/{doi} only when OpenAlex is set.
type DOIRecord struct {
	DOI      string
	Type     string // Crossref work type; "journal" etc. are containers
	Title    string
	Abstract string
	Authors  []string
	Venue    string
	Year     int
	Crossref bool // false: Crossref answers 404 (DataCite-only DOI)
	OpenAlex *OpenAlexWork
}

// OpenAlexWork is the subset of an OpenAlex work the catalog reads.
type OpenAlexWork struct {
	ID          string
	LandingPage string // e.g. an arXiv abs page, which the catalog turns into an arXiv paper
	PDFURL      string // an open-access PDF the catalog probes and downloads
}

// DOIs is the deterministic Crossref/OpenAlex the test stand sees.
var DOIs = []DOIRecord{
	{
		// Metadata only: no OpenAlex record, no PDF anywhere. The reader shows
		// the card and the assistant works from the abstract.
		DOI:      "10.5555/fixture.metadata-only",
		Type:     "journal-article",
		Title:    "Closed Access Fixture: Metadata Without Any Full Text",
		Abstract: "A journal article whose publisher offers no open-access copy.",
		Authors:  []string{"Nora Closed", "Omar Paywall"},
		Venue:    "Journal of Deterministic Fixtures",
		Year:     2022,
		Crossref: true,
	},
	{
		// OpenAlex knows an open-access PDF: the catalog downloads it (web_pdf).
		DOI:      "10.5555/fixture.open-access-pdf",
		Type:     "journal-article",
		Title:    "Open Access Fixture: Publisher PDF Discovered Through OpenAlex",
		Abstract: "A journal article with a freely downloadable PDF.",
		Authors:  []string{"Pia Open"},
		Venue:    "Journal of Deterministic Fixtures",
		Year:     2021,
		Crossref: true,
		OpenAlex: &OpenAlexWork{ID: "https://openalex.org/W5555000002", PDFURL: "https://api.openalex.org/oa/paper-oa-1p.pdf"},
	},
	{
		// OpenAlex maps the DOI to an arXiv paper: the catalog opens the arXiv
		// version (TeX-first parse, page cites) instead of a bare DOI record.
		DOI:      "10.5555/fixture.arxiv-twin",
		Type:     "journal-article",
		Title:    "Test Paper Three: Trending Feed Filler A",
		Authors:  []string{"Dan Feed", "Eve Feed"},
		Venue:    "Proceedings of Fixtures",
		Year:     2023,
		Crossref: true,
		OpenAlex: &OpenAlexWork{ID: "https://openalex.org/W5555000003", LandingPage: "https://arxiv.org/abs/2301.00003"},
	},
	{
		// A whole journal, not a paper.
		DOI:      "10.5555/fixture.journal",
		Type:     "journal",
		Title:    "Journal of Deterministic Fixtures",
		Crossref: true,
	},
}

// Synthetic DOIs, like synthetic arXiv ids, give a scenario a record nobody
// created before: 10.5555/closed.NNNNN has metadata only, 10.5555/oa.NNNNN
// carries an open-access PDF known to OpenAlex.
const (
	SyntheticDOIClosed = "10.5555/closed."
	SyntheticDOIOpen   = "10.5555/oa."
)

func syntheticDOI(doi string) (DOIRecord, bool) {
	var suffix string
	switch {
	case strings.HasPrefix(doi, SyntheticDOIClosed):
		suffix = strings.TrimPrefix(doi, SyntheticDOIClosed)
	case strings.HasPrefix(doi, SyntheticDOIOpen):
		suffix = strings.TrimPrefix(doi, SyntheticDOIOpen)
	default:
		return DOIRecord{}, false
	}
	if len(suffix) != 5 {
		return DOIRecord{}, false
	}
	rec := DOIRecord{
		DOI:      doi,
		Type:     "journal-article",
		Title:    "Synthetic DOI Fixture " + suffix + ": Minted For One Test Run",
		Abstract: "A synthetic Crossref record generated by fake-scholar for " + doi + ".",
		Authors:  []string{"Syn Thetic", "Doi Fixture"},
		Venue:    "Journal of Deterministic Fixtures",
		Year:     2022,
		Crossref: true,
	}
	if strings.HasPrefix(doi, SyntheticDOIOpen) {
		rec.OpenAlex = &OpenAlexWork{ID: "https://openalex.org/W" + suffix, PDFURL: "https://api.openalex.org/oa/paper-oa-1p.pdf"}
	}
	return rec, true
}

// FindDOI returns the record for a DOI (case-insensitive).
func FindDOI(doi string) (DOIRecord, bool) {
	doi = strings.ToLower(strings.TrimSpace(doi))
	if rec, ok := syntheticDOI(doi); ok {
		return rec, true
	}
	for _, d := range DOIs {
		if strings.ToLower(d.DOI) == doi {
			return d, true
		}
	}
	return DOIRecord{}, false
}
